# Alfredo Skybot - Alfredo Bot for Bluesky
# Copyright (C) 2026 Yehuda Bernáth

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Deploy

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: deploy

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version-file: ".nvmrc"
            cache: npm

        - name: Install dependencies
          run: npm ci

        - name: Deploy to Cloudflare Workers
          uses: cloudflare/wrangler-action@v4
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            vars: |
              USER_AGENT_URL
          env:
            USER_AGENT_URL: ${{ github.server_url }}/${{ github.repository }}
